# Builds an image for arm architecture processor
# cf. http://www.hotblackrobotics.com/en/blog/2018/01/22/docker-images-arm/

# Use an official Python runtime as a parent image
FROM armhf/python:3.5-slim

# Copy the qemu hypervisor to build an image runnable on ARM architecture (for Rapberry for instance)
COPY ./src/package/qemu-arm-static /usr/bin/qemu-arm-static

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r src/package/requirements.txt

ENV PYTHONPATH /app:/usr/local/lib/python3.5/site-packages

# Run app.py when the container launches
CMD ["python3", "/app/src/main/python/process/archiving/delib_archiver.py"]
